const dotenv = require('dotenv');
dotenv.config();
  // variablename: process.env.ENV_NAME_HERE
   const config = {
     acctName: process.env.ACCT_NAME,
     s3AccessKeyId: process.env.S3_ACCESS_KEY_ID,
     s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
     awsCognitoKeyId: process.env.AWS_COGNITO_KEY_ID,
     awsCognitoAccessKey: process.env.AWS_COGNITO_ACCESS_KEY,
     awsPoolId: process.env.AWS_POOL_ID,
     awsPoolClientId: process.env.AWS_POOL_CLIENT_ID,
     awsEuroId: process.env.AWS_EURO_ID,
     awsEuroAccessKey: process.env.AWS_EURO_ACCESS_KEY,
     dbHost: process.env.DB_HOST,
     dbPort: process.env.DB_PORT,
     wif: process.env.WIF,
     wifActive: process.env.WIF_ACTIVE,
     memo: process.env.MEMO,
     admin: process.env.ADMIN,
     jwtKey: process.env.JWT_KEY,
     authJwt: process.env.AUTH_JWT,
     bananaKey: process.env.BANANA_KEY,
     hiveSearcherAuth: process.env.HIVE_SEARCHER_AUTH,
     appSentryDsn: process.env.APP_SENTRY_DSN,
     appRedisHost: process.env.APP_REDIS_HOST,
     appRedditMqHost: process.env.APP_REDDITMQ_HOST,
     authApiClientId: process.env.AUTH_API_CLIENT_ID,
     authJwtSecret: process.env.AUTH_JWT_SECRET,
     authSessionSecret: process.env.AUTH_SESSION_SECRET,
     authWifMemo: process.env.AUTH_WIF_MEMO,
     authPubMemo: process.env.AUTH_PUB_MEMO,
     awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID,
     awsSecretKey: process.env.AWS_SECRET_KEY,
     awsCloudSearchAccessKeyId: process.env.AWS_CLOUDSEARCH_ACCESS_KEY_ID,
     awsCloudSearchSecretKey: process.env.AWS_CLOUDSEARCH_SECRET_KEY,
     awsCloudSearchEndpoint: process.AWS_CLOUDSEARCH_ENDPOINT,
     wasabiEndpoint: process.env.WASABI_ENDPOINT,
     wasabiAccessKeyId: process.env.WASABI_ACCESS_KEY_ID,
     wasabiSecretKey: process.env.WASABI_SECRET_KEY,
     encoderSecret: process.env.ENCODER_SECRET,
     bunnyCdnSecurityKey: process.env.BUNNY_CDN_SECURITY_KEY,
     hiveSqlHost: process.env.HIVESQL_HOST,
     hiveSqlUser: process.env.HIVESQL_USER,
     hiveSqlPassword: process.env.HIVESQL_PASSWORD,
     hiveSqlDatabase: process.env.HIVESQL_DATABASE,
     threespeakPostingWif: process.env.THREESPEAK_POSTING_WIF,
     threespeakActiveWif: process.env.THREESPEAK_ACTIVE_WIF,
     googleRecaptchaKey: process.env.GOOGLE_RECAPTCHA_KEY
  };

exports.config = config;
